# Build settings
markdown:           kramdown
permalink:          pretty


# Dependencies
markdown:           kramdown
highlighter:        rouge
gems:               [jekyll-paginate]

# Permalinks
permalink:          pretty

# Setup
title:              "Making Things/Writing Things"
tagline:
description:        "E107|Pierce College|SP19"
host:               127.0.0.1
url:                ""
baseurl:            "/test"
email:              jloan@pierce.ctc.edu


paginate:           5
layout:             blog-post

# Custom vars
version:            2.0.0
